### ISSUE TITLE
根据你们这个工程我要如何封装成sdk?

### ISSUE THREAD

**Issue by zuocai1993** [bayescom/EasyAds-iOS#7]
根据你们这个工程我要如何封装成sdk?
目前不想让调用者看到实现源码 不知道这块该如何实现

**Comment by lightyear5235** [comment]
你们可以自己将工程打包成sdk

**Comment by zuocai1993** [comment]
> 你们可以自己将工程打包成sdk

直接打包成sdk

https://github.com/bayescom/iOS_AdvanceSDK  这个sdk的话里面的文件还是可以看到的。
我是想把文件完全做成framework  可是没有思路。请大神提供一下简单思路

**Comment by zuocai1993** [comment]
已解决
